# CDB1 CouchDB and Internet Security Group/Roles
- name: Creating "CDB1 CouchDB and Internet" Security Group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ cdb1-internet-security-group }}'

- name: Attach Security Group rules (TCP/CouchDB ports) for "CDB1 CouchDB and Internet"
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    direction: '{{ item.direction }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.ip_prefix }}'
    state: present'
  loop: '{{ cdb1-internet-security-group-roles }}'

# CDB1 CouchDB Ingress/Egress to/from CDB0 Security Group/Roles
- name: Creating "CDB1 CouchDB Ingress/Egress to/from CDB0" Security Group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ cdb1-cdb0-couch-security-group }}'

- name: Attach Security Group rules (CouchDB ports) for "CDB1 CouchDB Ingress/Egress to/from CDB0"
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    direction: '{{ item.direction }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ couchdb_instance_0_ip }}/32'
    state: present'
  loop: '{{ cdb1-cdb0-couch-security-group-roles }}'

# CDB1 CouchDB Ingress/Egress to/from CDB2 Security Group/Roles
- name: Creating "CDB1 CouchDB Ingress/Egress to/from CDB2" Security Group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ cdb1-cdb2-couch-security-group }}'

- name: Attach Security Group rules (CouchDB ports) for "CDB1 CouchDB Ingress/Egress to/from CDB2"
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    direction: '{{ item.direction }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ couchdb_instance_2_ip }}/32'
    state: present'
  loop: '{{ cdb1-cdb2-couch-security-group-roles }}'

# CDB1 CouchDB Ingress/Egress to/from Web Server Security Group/Roles
- name: Creating "CDB1 CouchDB Ingress/Egress to/from Web Server" Security Group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ cdb1-webserver-couch-security-group }}'

- name: Attach Security Group rules (CouchDB ports) for "CDB1 CouchDB Ingress/Egress to/from Web Server"
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    direction: '{{ item.direction }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'
    state: present'
  loop: '{{ cdb1-webserver-couch-security-group-roles }}'

# CDB1 HTTP/S Egress to Web Server Security Group/Roles
- name: Creating "CDB1 HTTP/S Egress to Web Server" Security Group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ ccdb1-webserver-https-security-group }}'

- name: Attach Security Group rules (HTTP/S ports) for "CDB1 HTTP/S Egress to Web Server"
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    direction: '{{ item.direction }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'
    state: present'
  loop: '{{ cdb1-webserver-https-security-group-roles }}'

# Setting additional Security Group list for CouchDB1
- name: Setting additional CouchDB1 instance rules list
  set_fact:
    couchdb1_sg: ["SSH access from all", 
     "CDB1 CouchDB and Internet",
     "CDB1 CouchDB Ingress/Egress to/from CDB0",
     "CDB1 CouchDB Ingress/Egress to/from CDB2",
     "CDB1 CouchDB Ingress/Egress to/from Web Server",
     "CDB1 HTTP/S Egress to Web Server"]

- debug:
    msg: "Security group(s) {{ couchdb1_sg }} have been created."

