# Create CouchDB instances on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_1c4g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2_uom
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ couchdb_instances }}'
  register: os_instance

# Create Twitter Harvester instance
- name: Create Twitter Harvester Instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_2c9g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2_uom
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ harvester_instance }}'
  register: os_instance

# Create Web Front End Instance
- name: Create Web Front-End Instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_2c9g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2_uom
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ web_front_end_instance }}'
  register: os_instance 

- debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined


