# CDB0 CouchDB Ingress from CDB1 Security Group (Pan 2021).
- name: Create "CDB0 CouchDB Ingress from CDB1" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Ingress from CDB1'
    description: 'Allowing traffic on CouchDB Ports from CDB1'
    state: present

# CDB0 CouchDB Ingress from CDB2 Security Group (Pan 2021).
- name: Create "CDB0 CouchDB Ingress from CDB2" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Ingress from CDB2'
    description: 'Allowing traffic on CouchDB Ports from CDB2'
    state: present

# CDB0 CouchDB Ingress from Webserver Security Group (Pan 2021).
- name: Create "CDB0 CouchDB Ingress from Webserver" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Ingress from Webserver'
    description: 'Allowing traffic on CouchDB Ports from Webserver'
    state: present

# CDB0 CouchDB and Internet Security Group (Pan 2021).
- name: Create "CDB0 CouchDB and Internet" Security Group
  os_security_group:
    name: 'CDB0 CouchDB and Internet'
    description: 'Allowing traffic on CouchDB Ports from Internet'
    state: present

# CDB0 CouchDB and Internet Security Group Roles (Pan 2021).
- name: Attach Security Group rules HTTP for "CDB0 CouchDB and Internet"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB and Internet'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '0.0.0.0/0'  

- name: Attach Security Group rules HTTP for "CDB0 CouchDB and Internet"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB and Internet'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '0.0.0.0/0'  

- name: Attach Security Group rules HTTP for "CDB0 CouchDB and Internet"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB and Internet'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '5984'
    port_range_max: '5984'
    remote_ip_prefix: '0.0.0.0/0' 

- name: Attach Security Group rules HTTP for "CDB0 CouchDB and Internet"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB and Internet'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '5984'
    port_range_max: '5984'
    remote_ip_prefix: '0.0.0.0/0' 

# CDB0 CouchDB Ingress from CDB1 Security Group Role (Pan 2021).
- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Ingress from CDB1"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Ingress from CDB1'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_1_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

# CDB0 CouchDB Ingress from CDB2 Security Group Role (Pan 2021).
- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Ingress from CDB2"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Ingress from CDB2'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_2_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

# CDB0 CouchDB Egress to CDB1 Security Group (Pan 2021).
- name: Create "CDB0 CouchDB Egress to CDB1" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Egress to CDB1'
    description: 'Allowing traffic on CouchDB Ports to CDB2'
    state: present

# CDB0 CouchDB Egress to CDB2 Security Group (Pan 2021).
- name: Create "CDB0 CouchDB Egress to CDB2" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Egress to CDB2'
    description: 'Allowing traffic on CouchDB Ports to CDB2'
    state: present

# CDB0 HTTP/HTTPS Egress to Webserver Security Group (Pan 2021).
- name: Create "CDB0 HTTP/HTTPS Egress to Webserver" Security Group
  os_security_group:
    name: 'CDB0 HTTP/HTTPS Egress to Webserver'
    description: 'Allowing traffic on HTTP and HTTPS Ports to Webserver'
    state: present

# CDB0 CouchDB Egress to Webserver Security Group (Pan 2021).
- name: Create "CDB0 CouchDB Egress to Webserver" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Egress to Webserver'
    description: 'Allowing CouchDB egress traffic to Webserver'
    state: present

# CDB0 CouchDB Egress to CDB1 Security Group Role (Pan 2021).
- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Egress to CDB1"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Egress to CDB1'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_1_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

# CDB0 CouchDB Egress to CDB2 Security Group Role (Pan 2021).
- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Egress to CDB2"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Egress to CDB2'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_2_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

# CDB0 HTTP/HTTPS Egress to Webserver Security Group Roles (Pan 2021).
- name: Attach Security Group rules (HTTP port) for "CDB0 HTTP/HTTPS Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB0 HTTP/HTTPS Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'  

- name: Attach Security Group rules (HTTPS port) for "CDB0 HTTP/HTTPS Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB0 HTTP/HTTPS Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '443'
    port_range_max: '443'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'  

# CDB0 CouchDB Egress to Webserver Security Group Role (Pan 2021).
- name: Attach Security Group rules (CouchDB port) for "CDB0 CouchDB Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '5984'
    port_range_max: '5984'
    remote_ip_prefix: '{{ web_front_end_ip }}/32' 

# CDB0 CouchDB Ingress from Webserver Security Group Role (Pan 2021).
- name: Attach Security Group rules (CouchDB port) for "CDB0 CouchDB Ingress from Webserver"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Ingress from Webserver'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '5984'
    port_range_max: '5984'
    remote_ip_prefix: '0.0.0.0/0' 

# Setting additional Security Group list for CouchDB0 (Pan 2021).
- name: Setting additional CouchDB0 instance SG rules list
  set_fact:
    couchdb0_sg: ["SSH access from all", 
     "CDB0 CouchDB Ingress from CDB1",
     "CDB0 CouchDB Egress to CDB1",
     "CDB0 CouchDB Ingress from CDB2",
     "CDB0 CouchDB Egress to CDB2",
     "CDB0 HTTP/HTTPS Egress to Webserver",
     "CDB0 CouchDB Egress to Webserver",
     "CDB0 CouchDB Ingress from Webserver", 
     "CDB0 CouchDB and Internet"]

- debug:
    msg: " Additional Security groups for CouchDB0 created: {{ couchdb0_sg }}"

# REFERENCES
# 
# Ansible 2021, Loops, viewed 1st May 2021, 
# <https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-simple-list>
# 
# Ansible 2021, os_security_group_rule - Add/Delete rule from an existing security group, viewed 1st May 2021, 
# <https://docs.ansible.com/ansible/2.5/modules/os_security_group_rule_module.html>
# 
# Ansible 2021, os_server - Create/Delete Compute Instances from Openstack, viewed 25th April 2021, <https://docs.ansible.com/ansible/2.4/os_server_module.html>
# 
# Ansible 2021, Tags, viewed 25th April 2021, 
# <https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html>.
# 
# Apache Software Foundation 2021, 2.2/ Cluster Setup, viewed 1st May 2021,
# <https://docs.couchdb.org/en/stable/setup/cluster.html>.
# 
# Eisenkot, G 2020, Security challenges and risks with infrastructure as code, viewed 21st May 2021,
# <https://bridgecrew.io/blog/security-challenges-and-risks-with-infrastructure-as-code/>
# 
# Harrower, M. and Bloch, M., 2006. MapShaper. org: A map generalization web service. IEEE Computer Graphics and Applications, 26(4), pp.22-27.
# 
# Internet Assigned Numbers Authority 2021, Service Name and Transport Protocol Port Number Registry, viewed 1st May 2021, <https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http>.
# 
# JGraph 2021, diagrams.net, viewed 1st April 2021, 
# <https://www.diagrams.net>.
# 
# Pan, A 2021, Workshop 9-10 Ansible, The University of Melbourne, Parkville, viewed 24th April 2021, <https://canvas.lms.unimelb.edu.au/courses/105440/files/7077574/download?download_frd=1>.
# 
# Pan, A 2021, Workshop 9-10 Ansible Code, The University of Melbourne, Parkville, viewed 24th April 2021, <https://canvas.lms.unimelb.edu.au/files/7112800/download?download_frd=1>.
# 
# The University of Melbourne 2021, Re:Cite, viewed 21st May 2021, 
# <https://library.unimelb.edu.au/recite>.
# 
# Tutorials Point 2021, YAML - Comments, viewed 1st May 2021, 
# <https://www.tutorialspoint.com/yaml/yaml_comments.htm>.
# 
# Vasiljevic, S 2020, Infrastructure As Code Demistifyed: IaC Benefits, Challenges and Best Practies, viewed 21st May 2021, 
# <https://superadmins.com/infrastructure-as-code-demystified-iac-benefits-challenges-best-practices/>