- name: Update pip
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  pip:
    name: ['openstacksdk==0.52']
    state: latest
# pip install openstacksdk