- debug:
    msg: " CouchDB instance 0 has IP {{ couchdb_instance_0_ip }}, {{ couchdb_instance_1_ip }}, {{ couchdb_instance_2_ip }}, {{ web_front_end_ip }}" 

# Create CouchDB 0 Ingress Security Groups
- name: Create "CDB0 CouchDB Ingress from CDB1" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Ingress from CDB1'
    description: 'Allowing traffic on CouchDB Ports from CDB1'
    state: present

# Create CouchDB 0 Ingress Security Groups
- name: Create "CDB0 CouchDB Ingress from CDB2" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Ingress from CDB2'
    description: 'Allowing traffic on CouchDB Ports from CDB2'
    state: present


- name: Create "CDB0 CouchDB Ingress from Webserver" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Ingress from Webserver'
    description: 'Allowing traffic on CouchDB Ports from Webserver'
    state: present


- name: Create "CDB0 CouchDB and Internet" Security Group
  os_security_group:
    name: 'CDB0 CouchDB and Internet'
    description: 'Allowing traffic on CouchDB Ports from Internet'
    state: present

- name: Attach Security Group rules HTTP for "CDB0 CouchDB and Internet"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB and Internet'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '0.0.0.0/0'  

- name: Attach Security Group rules HTTP for "CDB0 CouchDB and Internet"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB and Internet'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '0.0.0.0/0'  


# Attach CouchDB Port rules to SG
- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Ingress from CDB1"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Ingress from CDB1'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_1_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Ingress from CDB2"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Ingress from CDB2'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_2_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'



# Create CouchDB 0 Egress Security Groups
- name: Create "CDB0 CouchDB Egress to CDB1" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Egress to CDB1'
    description: 'Allowing traffic on CouchDB Ports to CDB2'
    state: present
- name: Create "CDB0 CouchDB Egress to CDB2" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Egress to CDB2'
    description: 'Allowing traffic on CouchDB Ports to CDB2'
    state: present

- name: Create "CDB0 HTTP/HTTPS Egress to Webserver" Security Group
  os_security_group:
    name: 'CDB0 HTTP/HTTPS Egress to Webserver'
    description: 'Allowing traffic on HTTP and HTTPS Ports to Webserver'
    state: present

- name: Create "CDB0 CouchDB Egress to Webserver" Security Group
  os_security_group:
    name: 'CDB0 CouchDB Egress to Webserver'
    description: 'Allowing CouchDB egress traffic to Webserver'
    state: present

# Attach CouchDB Port rules to SG
- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Egress to CDB1"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Egress to CDB1'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_1_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

- name: Attach Security Group rules (CouchDB ports) for "CDB0 CouchDB Egress to CDB2"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Egress to CDB2'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '{{ item }}'
    port_range_max: '{{ item }}'
    remote_ip_prefix: '{{ couchdb_instance_2_ip }}/32'
    state: present
  loop: '{{ couchdb_ports }}'

- name: Attach Security Group rules (HTTP port) for "CDB0 HTTP/HTTPS Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB0 HTTP/HTTPS Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '80'
    port_range_max: '80'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'  

- name: Attach Security Group rules (HTTPS port) for "CDB0 HTTP/HTTPS Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB0 HTTP/HTTPS Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '443'
    port_range_max: '443'
    remote_ip_prefix: '{{ web_front_end_ip }}/32'  

- name: Attach Security Group rules (CouchDB port) for "CDB0 CouchDB Egress to Webserver"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Egress to Webserver'
    protocol: 'tcp'
    direction: 'egress'
    port_range_min: '5984'
    port_range_max: '5984'
    remote_ip_prefix: '{{ web_front_end_ip }}/32' 

- name: Attach Security Group rules (CouchDB port) for "CDB0 CouchDB Ingress from Webserver"
  os_security_group_rule:
    security_group: 'CDB0 CouchDB Ingress from Webserver'
    protocol: 'tcp'
    direction: 'ingress'
    port_range_min: '5984'
    port_range_max: '5984'
    remote_ip_prefix: '0.0.0.0/0' 


# Setting additional rules list
- name: Setting additional CouchDB0 instance rules list
  set_fact:
    couchdb0_sg: ["SSH access from all", 
     "CDB0 CouchDB Ingress from CDB1",
     "CDB0 CouchDB Egress to CDB1",
     "CDB0 CouchDB Ingress from CDB2",
     "CDB0 CouchDB Egress to CDB2",
     "CDB0 HTTP/HTTPS Egress to Webserver",
     "CDB0 CouchDB Egress to Webserver",
     "CDB0 CouchDB Ingress from Webserver", 
     "CDB0 CouchDB and Internet"]

- debug:
    msg: "Security group(s) {{ couchdb0_sg }} have been created."

