# Create CouchDB Instance 0 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_1c4g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    volumes: 'couchdb0_vol_1'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ couchdb_instance_0 }}'
  register: os_instance

# Settig CouchDB instance 0 fact
- name: Setting couchdb_instance_0_ip fact
  set_fact:
    couchdb_instance_0_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create CouchDB Instance 1 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_1c4g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    volumes: 'couchdb1_vol_1'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ couchdb_instance_1 }}'
  register: os_instance

# Settig CouchDB instance 1 fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    couchdb_instance_1_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create CouchDB Instance 2 on MRC
- name: Create CouchDB instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_1c4g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    volumes: 'couchdb2_vol_1'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ couchdb_instance_2 }}'
  register: os_instance

# Settig CouchDB Instance 2 IP fact
- name: Setting couchdb_instance_1_ip fact
  set_fact:
    couchdb_instance_2_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# Create Web Front End Instance
- name: Create Web Front-End Instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor_2c9g }}'
    availability_zone: '{{ availability_zone }}'
    nics: 
      - net-name: qh2-uom
    security_groups: '{{ sg_initial }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ web_front_end_instance }}'
  register: os_instance 

# Settig Web front end ip IP fact
- name: Setting web front end ip fact
  set_fact:
    web_front_end_ip: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'  
  when: item.openstack is defined

# REFERENCES
# 
# Ansible 2021, Loops, viewed 1st May 2021, 
# <https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-simple-list>
# 
# Ansible 2021, os_security_group_rule - Add/Delete rule from an existing security group, viewed 1st May 2021, 
# <https://docs.ansible.com/ansible/2.5/modules/os_security_group_rule_module.html>
# 
# Ansible 2021, os_server - Create/Delete Compute Instances from Openstack, viewed 25th April 2021, <https://docs.ansible.com/ansible/2.4/os_server_module.html>
# 
# Ansible 2021, Tags, viewed 25th April 2021, 
# <https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html>.
# 
# Apache Software Foundation 2021, 2.2/ Cluster Setup, viewed 1st May 2021,
# <https://docs.couchdb.org/en/stable/setup/cluster.html>.
# 
# Eisenkot, G 2020, Security challenges and risks with infrastructure as code, viewed 21st May 2021,
# <https://bridgecrew.io/blog/security-challenges-and-risks-with-infrastructure-as-code/>
# 
# Harrower, M. and Bloch, M., 2006. MapShaper. org: A map generalization web service. IEEE Computer Graphics and Applications, 26(4), pp.22-27.
# 
# Internet Assigned Numbers Authority 2021, Service Name and Transport Protocol Port Number Registry, viewed 1st May 2021, <https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http>.
# 
# JGraph 2021, diagrams.net, viewed 1st April 2021, 
# <https://www.diagrams.net>.
# 
# Pan, A 2021, Workshop 9-10 Ansible, The University of Melbourne, Parkville, viewed 24th April 2021, <https://canvas.lms.unimelb.edu.au/courses/105440/files/7077574/download?download_frd=1>.
# 
# Pan, A 2021, Workshop 9-10 Ansible Code, The University of Melbourne, Parkville, viewed 24th April 2021, <https://canvas.lms.unimelb.edu.au/files/7112800/download?download_frd=1>.
# 
# The University of Melbourne 2021, Re:Cite, viewed 21st May 2021, 
# <https://library.unimelb.edu.au/recite>.
# 
# Tutorials Point 2021, YAML - Comments, viewed 1st May 2021, 
# <https://www.tutorialspoint.com/yaml/yaml_comments.htm>.
# 
# Vasiljevic, S 2020, Infrastructure As Code Demistifyed: IaC Benefits, Challenges and Best Practies, viewed 21st May 2021, 
# <https://superadmins.com/infrastructure-as-code-demystified-iac-benefits-challenges-best-practices/>