# CDB1 CouchDB and Internet Security Group (Pan 2021).
cdb1_internet_security_group: 
  - name: CDB1 CouchDB and Internet
    description: "Allowing traffic on CouchDB Ports from Internet"

# CDB1 CouchDB and Internet Security Group Roles (Pan 2021).
cdb1_internet_security_group_roles: 
  - name: CDB1 CouchDB and Internet
    protocol: tcp
    direction: ingress
    port_range_min: 80
    port_range_max: 80
    ip_prefix: 0.0.0.0/0
  - name: CDB1 CouchDB and Internet 
    protocol: tcp
    direction: egress
    port_range_min: 80
    port_range_max: 80
    ip_prefix: 0.0.0.0/0
  - name: CDB1 CouchDB and Internet 
    protocol: tcp
    direction: ingress
    port_range_min: 5984
    port_range_max: 5984
    ip_prefix: 0.0.0.0/0
  - name: CDB1 CouchDB and Internet 
    protocol: tcp
    direction: egress
    port_range_min: 5984
    port_range_max: 5984
    ip_prefix: 0.0.0.0/0

# CDB1 CouchDB Ingress/Egress to/from CDB0 Security Group (Pan 2021).
cdb1_cdb0_couch_security_group:
  - name: CDB1 CouchDB Ingress/Egress to/from CDB0
    description: "Allowing traffic on CouchDB Ports to/from CDB0"

# CDB1 CouchDB Ingress/Egress to/from CDB0 Security Group Roles (Pan 2021).
cdb1_cdb0_couch_security_group_roles:
  - name: CDB1 CouchDB Ingress/Egress to/from CDB0
    protocol: tcp
    direction: ingress
    port_range_min: 4369
    port_range_max: 4369
  - name: CDB1 CouchDB Ingress/Egress to/from CDB0
    protocol: tcp
    direction: ingress
    port_range_min: 5984
    port_range_max: 5984
  - name: CDB1 CouchDB Ingress/Egress to/from CDB0
    protocol: tcp
    direction: ingress
    port_range_min: 9100
    port_range_max: 9100
  - name: CDB1 CouchDB Ingress/Egress to/from CDB0
    protocol: tcp
    direction: egress
    port_range_min: 4369
    port_range_max: 4369
  - name: CDB1 CouchDB Ingress/Egress to/from CDB0
    protocol: tcp
    direction: egress
    port_range_min: 5984
    port_range_max: 5984
  - name: CDB1 CouchDB Ingress/Egress to/from CDB0
    protocol: tcp
    direction: egress
    port_range_min: 9100
    port_range_max: 9100

# CDB1 CouchDB Ingress/Egress to/from CDB2 Security Group (Pan 2021).
cdb1_cdb2_couch_security_group:
  - name: CDB1 CouchDB Ingress/Egress to/from CDB2
    description: "Allowing traffic on CouchDB Ports to/from CDB2"

# CDB1 CouchDB Ingress/Egress to/from CDB2 Security Group Roles (Pan 2021).
cdb1_cdb2_couch_security_group_roles:
  - name: CDB1 CouchDB Ingress/Egress to/from CDB2
    protocol: tcp
    direction: ingress
    port_range_min: 4369
    port_range_max: 4369
  - name: CDB1 CouchDB Ingress/Egress to/from CDB2
    protocol: tcp
    direction: ingress
    port_range_min: 5984
    port_range_max: 5984
  - name: CDB1 CouchDB Ingress/Egress to/from CDB2
    protocol: tcp
    direction: ingress
    port_range_min: 9100
    port_range_max: 9100
  - name: CDB1 CouchDB Ingress/Egress to/from CDB2
    protocol: tcp
    direction: egress
    port_range_min: 4369
    port_range_max: 4369
  - name: CDB1 CouchDB Ingress/Egress to/from CDB2
    protocol: tcp
    direction: egress
    port_range_min: 5984
    port_range_max: 5984
  - name: CDB1 CouchDB Ingress/Egress to/from CDB2
    protocol: tcp
    direction: egress
    port_range_min: 9100
    port_range_max: 9100

# CDB1 CouchDB Ingress/Egress to/from Web Server Security Group (Pan 2021).
cdb1_webserver_couch_scurity_group:
  - name: CDB1 CouchDB Ingress/Egress to/from Web Server
    description: "Allowing traffic on CouchDB Port 5984 to/from Web Server"

# CDB1 CouchDB Ingress/Egress to/from Web Server Security Group Roles (Pan 2021).
cdb1_webserver_couch_security_group_roles:
  - name: CDB1 CouchDB Ingress/Egress to/from Web Server
    protocol: tcp
    direction: ingress
    port_range_min: 5984
    port_range_max: 5984
  - name: CDB1 CouchDB Ingress/Egress to/from Web Server
    protocol: tcp
    direction: egress
    port_range_min: 5984
    port_range_max: 5984

# CDB1 HTTP/S Egress to Web Server Security Group (Pan 2021).
cdb1_webserver_https_security_group:
  - name: CDB1 HTTP/S Egress to Web Server
    description: "Allowing HTTP/S egress traffic to Web Server"

# CDB1 HTTP/S Egress to Web Server Security Group Roles (Pan 2021).
cdb1_webserver_https_security_group_roles:
  - name: CDB1 HTTP/S Egress to Web Server
    protocol: tcp
    direction: egress
    port_range_min: 80
    port_range_max: 80
  - name: CDB1 HTTP/S Egress to Web Server
    protocol: tcp
    direction: egress
    port_range_min: 443
    port_range_max: 443

# REFERENCES
# 
# Ansible 2021, Loops, viewed 1st May 2021, 
# <https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-simple-list>
# 
# Ansible 2021, os_security_group_rule - Add/Delete rule from an existing security group, viewed 1st May 2021, 
# <https://docs.ansible.com/ansible/2.5/modules/os_security_group_rule_module.html>
# 
# Ansible 2021, os_server - Create/Delete Compute Instances from Openstack, viewed 25th April 2021, <https://docs.ansible.com/ansible/2.4/os_server_module.html>
# 
# Ansible 2021, Tags, viewed 25th April 2021, 
# <https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html>.
# 
# Apache Software Foundation 2021, 2.2/ Cluster Setup, viewed 1st May 2021,
# <https://docs.couchdb.org/en/stable/setup/cluster.html>.
# 
# Eisenkot, G 2020, Security challenges and risks with infrastructure as code, viewed 21st May 2021,
# <https://bridgecrew.io/blog/security-challenges-and-risks-with-infrastructure-as-code/>
# 
# Harrower, M. and Bloch, M., 2006. MapShaper. org: A map generalization web service. IEEE Computer Graphics and Applications, 26(4), pp.22-27.
# 
# Internet Assigned Numbers Authority 2021, Service Name and Transport Protocol Port Number Registry, viewed 1st May 2021, <https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http>.
# 
# JGraph 2021, diagrams.net, viewed 1st April 2021, 
# <https://www.diagrams.net>.
# 
# Pan, A 2021, Workshop 9-10 Ansible, The University of Melbourne, Parkville, viewed 24th April 2021, <https://canvas.lms.unimelb.edu.au/courses/105440/files/7077574/download?download_frd=1>.
# 
# Pan, A 2021, Workshop 9-10 Ansible Code, The University of Melbourne, Parkville, viewed 24th April 2021, <https://canvas.lms.unimelb.edu.au/files/7112800/download?download_frd=1>.
# 
# The University of Melbourne 2021, Re:Cite, viewed 21st May 2021, 
# <https://library.unimelb.edu.au/recite>.
# 
# Tutorials Point 2021, YAML - Comments, viewed 1st May 2021, 
# <https://www.tutorialspoint.com/yaml/yaml_comments.htm>.
# 
# Vasiljevic, S 2020, Infrastructure As Code Demistifyed: IaC Benefits, Challenges and Best Practies, viewed 21st May 2021, 
# <https://superadmins.com/infrastructure-as-code-demystified-iac-benefits-challenges-best-practices/>