# Harvester Security Groups
security_group_initial: 
  - name: SSH access from all
    description: "Allow SSH access from anywhere"
    protocol: tcp
    direction: ingress
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0